#!/bin/sh
#Dockerを立ち上げてから実行する。
#~/docker/nagoya/wwwにコンテンツを配置

git clone https://github.com/nagonagoya/Scheduler.git ~/docker/nagoya/www/Scheduler
docker run -d -p 80:80 -v ~/docker/nagoya/www/Scheduler:/var/www/html --name nagoya junendocreater/php
